name: 'Terraform check'
on:
  push:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_check.yml@main
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
